trigger:
- master

jobs:
  - job: test
    strategy:
      matrix:
        Python36:
          PYTHON_VERSION: '3.7.2'
    displayName: Test
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'
      - bash: |
            sudo apt-get install -y libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 ffmpeg libav-tools
      - bash: |
            sudo apt-get install -y xvfb
      - bash: |
            sudo apt-get install -y i3-wm
      - bash: |
            sudo apt-get install -y python3-tk
      - bash: |
            sudo apt-get install -y idle
      - bash: |
            sudo apt-get install -y xdotool
      - bash: |
          python3 -c 'import sys; print(sys.version); print(sys.platform)'
        displayName: Report Python version
      - bash: |
          python3 -m pip install tox
        displayName: Install tox
      - bash: |
          tox
        displayName: tox
